In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
import pandas as pd

pd.set_option('display.max_rows', 200, 'display.max_columns', 100)

### Listing files in the data directory

In [2]:
os.listdir('data/')

['sample_submission.csv',
 'click_log.csv',
 'Training Data.csv',
 'Pre-Read.txt',
 'Test Data.csv',
 'cleaned']

In [3]:
!cat data/Pre-Read.txt

### Reading the provided data

In [4]:
df_train = pd.read_csv('data/Training Data.csv')
df_test = pd.read_csv('data/Test Data.csv')
sample_submission = pd.read_csv('data/sample_submission.csv')
click_log = pd.read_csv('data/click_log.csv')

In [5]:
df_train.head()

,clientid_cr,clmbuserid_cr,conversiontime_cr,imprid_cr,adslotdimid_cr,algo_cr,audiences_cr,clickbid_cr,geodimid_cr,ip_cr,itemcolumbiaid_cr,itemid_cr,position_cr,pubclientid_cr,refurl_cr,siteId_cr,templateid_cr,goalid_cr,time_cr,adLogType_cr,v_cr,allAudiences_cr,pricingtype_cr,osId_cr,browserId_cr,cityId_cr,stateId_cr,modelDimId_cr,lookUpFrom_cr,connTypeDimId_cr,ispDimId_cr,countryDimId_cr,goalTypeId_cr,conversionDurationInMillis_cr,impressionTimeInMillis_cr,clickTimeInMillis_cr,osVerDimId_cr,uuidSource_cr,geoGrpDimId_cr,stateGrpDimId_cr,deviceId_cr,uvh_cr,uv_cr,platformId_cr,sdkVersion_cr,usrClusterId_cr,cityGrpDimId_cr,siteClusterIds_cr,refClusterId_cr,paid_cr,spend_cr,attributionType_cr,conversionid_cr,optimize_on_cr,bundleId_cr,conversion_fraud
0,75694,31629cd0-0b34-460f-aa61-80c3234e1225-1sjfw,1.620000e+12,01649076-c77f-4d70-afc8-213535427147-1sjd4,321300,38.0,"8gw,o3b",2.869316,144,XXX.XXX.XXX.XXX,5488088,49504155,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4140.0,6384,1.620000e+12,2,1.0,"7dn,6hs,35g,ome,omf,l32,nqo,2ws,qqo,lo4,oos,2w...",16,196058.0,129639.0,436.0,1806.0,202038.0,2,264496,280429.0,144.0,10,2332.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348022.0,NaN,NaN,NaN,NaN,NaN,333495,348007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,75694,4c98f114-c34c-48f4-84d6-50fc8e9b6d65-10wgg,1.620000e+12,f84d83b9-b757-4f97-9813-34f8dcc57cc5-1sjfw,129239,38.0,"8kv,2vk,8gw,2vl",2.790000,144,XXX.XXX.XXX.XXX,5488773,49504157,1.0,15240,https%3A%2F%2Fwww.cricbuzz.com%2Flive-cricket-...,178,663.0,6384,1.620000e+12,2,1.0,"h9r,35j,7dx,592,lo4,5o2,gau,75y,k8l,2ve,k8p,8k...",16,196058.0,129639.0,10314.0,1817.0,202038.0,2,264496,136127.0,144.0,10,3201.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348024.0,NaN,NaN,NaN,NaN,NaN,NaN,348010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,75694,cd92087a-54b0-4911-bc3d-1144a3c2babd-1sjlg,1.620000e+12,061edef6-3d9d-408b-884a-ad840e6930ce-10o78,321554,21.0,"8gw,o3b",2.790000,144,XXX.XXX.XXX.XXX,5488088,49504160,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4144.0,6384,1.620000e+12,2,1.0,"7dn,oy7,nqo,41j,2ws,lo4,oos,oou,apc,5o2,o6b,ox...",16,196058.0,129639.0,0.0,1812.0,202038.0,2,264503,172725.0,144.0,10,2821.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348027.0,NaN,NaN,NaN,NaN,NaN,128491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,75694,f79f3de7-5edb-4319-9549-117f47996066-10wrk,1.620000e+12,0a937239-9091-4bb7-b26b-37d4bb29e50b-10oa0,321300,38.0,"8gw,o3b",2.790000,144,XXX.XXX.XXX.XXX,5488088,49504155,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4140.0,6384,1.620000e+12,2,1.0,"p1b,7dn,6hs,jyq,35g,h98,oul,nqo,2ws,lo4,p12,2w...",16,196058.0,129639.0,10300.0,1815.0,202038.0,2,264496,136127.0,144.0,10,3144.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348023.0,NaN,NaN,NaN,NaN,NaN,"232,809,333,496",348007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,30431,01fd1a8a-c3f8-4b57-94ff-66318d0f63c7-1sjts,1.620000e+12,0d46d0d4-8fc6-4d95-aaa1-406354a8400c-1sjo8,355768,21.0,NaN,NaN,144,XXX.XXX.XXX.XXX,5614054,53607445,1.0,1,NaN,3296,NaN,3370,1.620000e+12,2,1.0,"761,75y",17,129311.0,129408.0,0.0,1818.0,0.0,2,264496,136127.0,144.0,10,42597.0,1.620000e+12,1.620000e+12,360833.0,1.0,348011.0,348025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,275.0,1.0,NaN,NaN,NaN,True

In [6]:
df_train.shape

(965, 56)

In [7]:
df_test.shape

(455, 56)

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 965 entries, 0 to 964
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   clientid_cr                    965 non-null    int64
 1   clmbuserid_cr                  965 non-null    object
 2   conversiontime_cr              965 non-null    float64
 3   imprid_cr                      965 non-null    object
 4   adslotdimid_cr                 965 non-null    int64
 5   algo_cr                        945 non-null    float64
 6   audiences_cr                   766 non-null    object
 7   clickbid_cr                    669 non-null    float64
 8   geodimid_cr                    965 non-null    int64
 9   ip_cr                          945 non-null    object
 10  itemcolumbiaid_cr              965 non-null    int64
 11  itemid_cr                      965 non-null    int64
 12  position_cr                    945 non-null    float64
 13  pubclientid_cr                 965 non-null    int64
 14  refurl_cr                      840 non-null    object
 15  siteId_cr                      965 non-null    int64
 16  templateid_cr                  858 non-null    float64
 17  goalid_cr                      965 non-null    int64
 18  time_cr                        965 non-null    float64
 19  adLogType_cr                   965 non-null    int64
 20  v_cr                           964 non-null    float64
 21  allAudiences_cr                918 non-null    object
 22  pricingtype_cr                 965 non-null    int64
 23  osId_cr                        944 non-null    float64
 24  browserId_cr                   944 non-null    float64
 25  cityId_cr                      945 non-null    float64
 26  stateId_cr                     945 non-null    float64
 27  modelDimId_cr                  944 non-null    float64
 28  lookUpFrom_cr                  965 non-null    int64
 29  connTypeDimId_cr               945 non-null    object
 30  ispDimId_cr                    945 non-null    float64
 31  countryDimId_cr                945 non-null    float64
 32  goalTypeId_cr                  965 non-null    int64
 33  conversionDurationInMillis_cr  945 non-null    float64
 34  impressionTimeInMillis_cr      945 non-null    float64
 35  clickTimeInMillis_cr           833 non-null    float64
 36  osVerDimId_cr                  944 non-null    float64
 37  uuidSource_cr                  945 non-null    float64
 38  geoGrpDimId_cr                 945 non-null    float64
 39  stateGrpDimId_cr               860 non-null    float64
 40  deviceId_cr                    111 non-null    float64
 41  uvh_cr                         0 non-null      float64
 42  uv_cr                          29 non-null     float64
 43  platformId_cr                  112 non-null    float64
 44  sdkVersion_cr                  7 non-null      object
 45  usrClusterId_cr                354 non-null    object
 46  cityGrpDimId_cr                621 non-null    float64
 47  siteClusterIds_cr              412 non-null    object
 48  refClusterId_cr                66 non-null     float64
 49  paid_cr                        194 non-null    float64
 50  spend_cr                       194 non-null    float64
 51  attributionType_cr             194 non-null    float64
 52  conversionid_cr                24 non-null     object
 53  optimize_on_cr                 40 non-null     object
 54  bundleId_cr                    5 non-null      float64
 55  conversion_fraud               965 non-null    bool
dtypes: bool(1), float64(31), int64(12), object(12)
memory usage: 415.7+ KB

### Unique value counts of training data and test data

In [9]:
df_train_unique = df_train.agg(['nunique']).transpose().reset_index()
df_train_unique.columns = ['column', 'unique_value_count']

In [10]:
display(df_train_unique)

                           column  unique_value_count
0                     clientid_cr                  57
1                   clmbuserid_cr                 896
2               conversiontime_cr                   1
3                       imprid_cr                 934
4                  adslotdimid_cr                 196
5                         algo_cr                  12
6                    audiences_cr                 440
7                     clickbid_cr                  58
8                     geodimid_cr                   9
9                           ip_cr                   1
10              itemcolumbiaid_cr                 130
11                      itemid_cr                 174
12                    position_cr                 166
13                 pubclientid_cr                  42
14                      refurl_cr                 399
15                      siteId_cr                  77
16                  templateid_cr                 136
17                      goalid_cr                  57
18                        time_cr                   1
19                   adLogType_cr                   2
20                           v_cr                   2
21                allAudiences_cr                 820
22                 pricingtype_cr                   3
23                        osId_cr                  15
24                   browserId_cr                  10
25                      cityId_cr                  82
26                     stateId_cr                  45
27                  modelDimId_cr                  22
28                  lookUpFrom_cr                   2
29               connTypeDimId_cr                   9
30                    ispDimId_cr                 136
31                countryDimId_cr                   9
32                  goalTypeId_cr                   1
33  conversionDurationInMillis_cr                 924
34      impressionTimeInMillis_cr                   2
35           clickTimeInMillis_cr                   2
36                  osVerDimId_cr                  32
37                  uuidSource_cr                   6
38                 geoGrpDimId_cr                   7
39               stateGrpDimId_cr                   8
40                    deviceId_cr                   3
41                         uvh_cr                   0
42                          uv_cr                  18
43                  platformId_cr                   3
44                  sdkVersion_cr                   3
45                usrClusterId_cr                 195
46                cityGrpDimId_cr                   6
47              siteClusterIds_cr                  54
48                refClusterId_cr                  26
49                        paid_cr                   1
50                       spend_cr                  27
51             attributionType_cr                   1
52                conversionid_cr                   5
53                 optimize_on_cr                   1
54                    bundleId_cr                   4
55               conversion_fraud                   2

In [11]:
drop_cols_df = df_train_unique[df_train_unique.unique_value_count.isin([0, 1])]

display(drop_cols_df)

                column  unique_value_count
2    conversiontime_cr                   1
9                ip_cr                   1
18             time_cr                   1
32       goalTypeId_cr                   1
41              uvh_cr                   0
49             paid_cr                   1
51  attributionType_cr                   1
53      optimize_on_cr                   1

In [12]:
to_drop_cols = drop_cols_df.column.values.tolist()

df_train = df_train.drop(columns=to_drop_cols)

In [13]:
df_train.head()

,clientid_cr,clmbuserid_cr,imprid_cr,adslotdimid_cr,algo_cr,audiences_cr,clickbid_cr,geodimid_cr,itemcolumbiaid_cr,itemid_cr,position_cr,pubclientid_cr,refurl_cr,siteId_cr,templateid_cr,goalid_cr,adLogType_cr,v_cr,allAudiences_cr,pricingtype_cr,osId_cr,browserId_cr,cityId_cr,stateId_cr,modelDimId_cr,lookUpFrom_cr,connTypeDimId_cr,ispDimId_cr,countryDimId_cr,conversionDurationInMillis_cr,impressionTimeInMillis_cr,clickTimeInMillis_cr,osVerDimId_cr,uuidSource_cr,geoGrpDimId_cr,stateGrpDimId_cr,deviceId_cr,uv_cr,platformId_cr,sdkVersion_cr,usrClusterId_cr,cityGrpDimId_cr,siteClusterIds_cr,refClusterId_cr,spend_cr,conversionid_cr,bundleId_cr,conversion_fraud
0,75694,31629cd0-0b34-460f-aa61-80c3234e1225-1sjfw,01649076-c77f-4d70-afc8-213535427147-1sjd4,321300,38.0,"8gw,o3b",2.869316,144,5488088,49504155,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4140.0,6384,2,1.0,"7dn,6hs,35g,ome,omf,l32,nqo,2ws,qqo,lo4,oos,2w...",16,196058.0,129639.0,436.0,1806.0,202038.0,2,264496,280429.0,144.0,2332.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348022.0,NaN,NaN,NaN,NaN,333495,348007.0,NaN,NaN,NaN,NaN,NaN,True
1,75694,4c98f114-c34c-48f4-84d6-50fc8e9b6d65-10wgg,f84d83b9-b757-4f97-9813-34f8dcc57cc5-1sjfw,129239,38.0,"8kv,2vk,8gw,2vl",2.790000,144,5488773,49504157,1.0,15240,https%3A%2F%2Fwww.cricbuzz.com%2Flive-cricket-...,178,663.0,6384,2,1.0,"h9r,35j,7dx,592,lo4,5o2,gau,75y,k8l,2ve,k8p,8k...",16,196058.0,129639.0,10314.0,1817.0,202038.0,2,264496,136127.0,144.0,3201.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348024.0,NaN,NaN,NaN,NaN,NaN,348010.0,NaN,NaN,NaN,NaN,NaN,True
2,75694,cd92087a-54b0-4911-bc3d-1144a3c2babd-1sjlg,061edef6-3d9d-408b-884a-ad840e6930ce-10o78,321554,21.0,"8gw,o3b",2.790000,144,5488088,49504160,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4144.0,6384,2,1.0,"7dn,oy7,nqo,41j,2ws,lo4,oos,oou,apc,5o2,o6b,ox...",16,196058.0,129639.0,0.0,1812.0,202038.0,2,264503,172725.0,144.0,2821.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348027.0,NaN,NaN,NaN,NaN,128491,NaN,NaN,NaN,NaN,NaN,NaN,True
3,75694,f79f3de7-5edb-4319-9549-117f47996066-10wrk,0a937239-9091-4bb7-b26b-37d4bb29e50b-10oa0,321300,38.0,"8gw,o3b",2.790000,144,5488088,49504155,1.0,2320,https%3A%2F%2Fwww.timesjobs.com%2Fcandidate%2F...,34,4140.0,6384,2,1.0,"p1b,7dn,6hs,jyq,35g,h98,oul,nqo,2ws,lo4,p12,2w...",16,196058.0,129639.0,10300.0,1815.0,202038.0,2,264496,136127.0,144.0,3144.0,1.620000e+12,1.620000e+12,199452.0,1.0,348011.0,348023.0,NaN,NaN,NaN,NaN,"232,809,333,496",348007.0,NaN,NaN,NaN,NaN,NaN,True
4,30431,01fd1a8a-c3f8-4b57-94ff-66318d0f63c7-1sjts,0d46d0d4-8fc6-4d95-aaa1-406354a8400c-1sjo8,355768,21.0,NaN,NaN,144,5614054,53607445,1.0,1,NaN,3296,NaN,3370,2,1.0,"761,75y",17,129311.0,129408.0,0.0,1818.0,0.0,2,264496,136127.0,144.0,42597.0,1.620000e+12,1.620000e+12,360833.0,1.0,348011.0,348025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275.0,NaN,NaN,True

In [14]:
df_train.loc[df_train.geodimid_cr == df_train.countryDimId_cr, ['geodimid_cr', 'countryDimId_cr']]

     geodimid_cr  countryDimId_cr
0            144            144.0
1            144            144.0
2            144            144.0
3            144            144.0
4            144            144.0
..           ...              ...
960          144            144.0
961          144            144.0
962          144            144.0
963          144            144.0
964          144            144.0

[944 rows x 2 columns]

In [15]:
df_train.loc[df_train.geodimid_cr != df_train.countryDimId_cr, ['geodimid_cr', 'countryDimId_cr']]

     geodimid_cr  countryDimId_cr
318       317759            434.0
504          144              NaN
505          144              NaN
506          144              NaN
507          144              NaN
508          144              NaN
509          144              NaN
510          144              NaN
511          144              NaN
512          144              NaN
513          144              NaN
514          144              NaN
515          144              NaN
516          144              NaN
517          144              NaN
518          144              NaN
519          144              NaN
520          144              NaN
521          144              NaN
522          144              NaN
523          144              NaN

In [16]:
df_train = df_train.drop(columns=['geodimid_cr'])

In [17]:
def missing_value_stats(df):
    num_rows = df.shape[0]
    # Missing value count by columns
    df_missing = df.isna().sum().reset_index()
    # Renaming columns
    df_missing.columns = ['column', 'missing_values']
    # Getting only those columns having missing values > 0
    df_missing = df_missing[df_missing['missing_values'] > 0]
    df_missing.reset_index(drop=True, inplace=True)
    # Calculating percentage of missing
    df_missing['missing_percentage'] = df_missing['missing_values'].apply(
        lambda missing_value: round((missing_value / num_rows) * 100, 2)
    )
    return df_missing

In [18]:
df_train_missing = missing_value_stats(df_train)

display(df_train_missing[df_train_missing.missing_percentage > 80].sort_values(by=['missing_percentage']))

             column  missing_values  missing_percentage
25    platformId_cr             853               88.39
23      deviceId_cr             854               88.50
30  refClusterId_cr             899               93.16
24            uv_cr             936               96.99
32  conversionid_cr             941               97.51
26    sdkVersion_cr             958               99.27
33      bundleId_cr             960               99.48

In [19]:
missing_cols = df_train_missing.loc[df_train_missing.missing_percentage > 90, 'column'].values.tolist()

df_train = df_train.drop(columns=missing_cols)

In [20]:
df_train.loc[~df_train.deviceId_cr.isna(), 
             ['deviceId_cr', 'osVerDimId_cr', 
              'modelDimId_cr', 'osId_cr', 'browserId_cr']].groupby(['deviceId_cr', 'modelDimId_cr', 
                                                                    'osId_cr', 'browserId_cr']).count()

                                                 osVerDimId_cr
deviceId_cr modelDimId_cr osId_cr  browserId_cr
129276.0    205409.0      129311.0 129408.0                  1
196041.0    0.0           129311.0 0.0                       2
                                   129408.0                 33
                                   129433.0                  7
            229195.0      129311.0 129408.0                  1
196047.0    0.0           196061.0 0.0                      12
            200709.0      196058.0 196030.0                  1
            202038.0      129300.0 129639.0                  5
                          196058.0 129639.0                 28
                          196063.0 129639.0                 16
            203206.0      196055.0 129639.0                  2
            205751.0      196063.0 129771.0                  1
            205776.0      196058.0 196034.0                  2

## Click logs

In [33]:
click_log.head()

,imprId,clmbUserId,adSltDimId,auds,allAuds,itemid,algo,advClientId,pubClientId,itmClmbLId,tmpltId,refUrl,clickBid,clickXForwardedFor,position,siteId,callIdentifier,adslotRatio,pricingType,usrClusterId,siteClusterIds,ctxCatId,uuidSource,clickIp,clickGeoId,esi,adBlockerDetectionValueId,bundleId,impressionServedTimeStamp,appver,topic,ip,geoDimId,countryDimId,geoGrpDimId,cityDimId,cityGrpDimId,stateDimId,stateGrpDimId,ispDimId,osDimId,osVerDimId,devTypeDimId,vendorDimId,modelDimId,connTypeDimId,browserDimId,refClusterId,fraud,cpa,imprUserId,optout
0,72efd138-0f6a-4aed-bd3f-9bdd70c0e869-1sjts,e91fcf75-a645-40f6-ab1f-411017d1d19a-631k,207251,"2vv,8k8,8gv,2vk,8gw,joa","7dm,cy9,5b2,oy7,p98,lo4,p12,p16,apc,p18,nqy,ic...",52696204,18,330,2310,5618155,5627.0,https%3A%2F%2Fnavbharattimes.indiatimes.com%2F...,13.10040,"103.212.158.109, 23.59.168.135, 124.124.201.229",0,16,B166b630l8021616125598649pzmfku8tlbktbqtjht65t,0.024,6.0,"333,734,333,729,333,000","128,527,333,734,333,000",205295-1,1,103.212.158.109,144.0,0.0,4.0,NaN,86.0,NaN,AdServe,122.176.114.222,144,144,348011.0,440.0,348005.0,1802.0,348021.0,136127.0,196063.0,199414.0,196047.0,196460.0,202038.0,264494,129639.0,NaN,NaN,NaN,NaN,NaN
1,210a7e16-6783-46a5-9246-c635db091490-3qpg,be37dc3a-d12b-4aa5-bd39-1e42ede9d6b9-6mhk,356952,"8gw,2vb,o3b","hkf,n5n,59j,p9q,n3p,p9t,o1o,41j,o1n,nyw,n3s,n5...",53622457,18,330,85030,5617956,5167.0,https%3A%2F%2Fwww.olx.in%2F,4.58514,"2409:4055:2e87:42e9:4dec:ae38:609e:8932, 49.44...",1,3290,q613U220R8891616126263941lu54rceq6xilidopi88m0k,1.000,16.0,NaN,NaN,205295-1,1,2409:4055:2e87:42e9:4dec:ae38:609e:8932,144.0,0.0,4.0,NaN,12.0,NaN,AdServe,2409:4055:2e87:42e9:4dec:ae38:609e:8932,144,144,348011.0,10292.0,348005.0,1812.0,348027.0,280429.0,196058.0,199452.0,196047.0,196460.0,202038.0,264496,129639.0,NaN,NaN,NaN,NaN,NaN
2,179d3fbb-3e10-435d-851d-f65029ef2eb4-10ntc,faceec73-d833-4bd6-b878-3bc27d2638dd-10uao,350086,"2vv,8k8,2vk,8gw","o1j,o1o,oy7,o1n,nyw,oww,lo4,p12,apc,358,5o2,o6...",53622457,38,330,2658,5617956,5657.0,https%3A%2F%2Ftimesofindia.indiatimes.com%2F,4.58514,"2405:201:c00e:4087:5838:cbcb:8571:e8c0, 49.44....",159934117,3,E660S185t880,1.000,16.0,333496,"333,734,128,527,333,000",205295-1,1,2405:201:c00e:4087:5838:cbcb:8571:e8c0,144.0,0.0,4.0,NaN,24.0,NaN,AdServe,2405:201:c00e:4087:5838:cbcb:8571:e8c0,144,144,348011.0,435.0,348008.0,129163.0,348023.0,280429.0,196063.0,199414.0,196047.0,196460.0,202038.0,264496,129639.0,NaN,NaN,NaN,NaN,NaN
3,79ce617b-88bf-46db-8069-6c892df6a306-1sjo8,113b0b7e-d065-4f14-861e-7bbb49683b15-10u2c,356952,"2vv,nqv,2vk,8gw,2vb,o3b","n7j,pf9,n90,n91,n98,o1o,nyw,o1n,lo4,nqv,igs,ap...",53622457,38,330,85030,5617956,5167.0,https%3A%2F%2Fwww.olx.in%2F,5.09460,"106.213.27.57, 23.58.93.149, 23.45.91.49",1,3290,G168U347S671616094330288c73g9hzkscvsrdrr8eklu,1.000,16.0,"333,494,333,507",NaN,205295-1,1,106.213.27.57,144.0,0.0,4.0,NaN,3.0,NaN,AdServe,106.213.27.57,144,144,348011.0,10255.0,348005.0,1804.0,348027.0,136127.0,129300.0,199522.0,196047.0,196460.0,202038.0,264496,129639.0,NaN,NaN,NaN,NaN,NaN
4,c8f88058-af7e-4284-8c88-2410d94f82e3-1sjo8,2b3dac7e-d4dd-4ae7-936d-1f9b4c73493d-h0hg,129239,"8kv,8j6,8k8,2vk,2vl,8gw,3si,2vt,2vv,nqv,2vb,8l...","n7j,nyw,592,n7x,n7z,qq5,apc,n8a,359,n8e,n8g,ap...",53622457,38,330,15240,5617956,663.0,https%3A%2F%2Fwww.cricbuzz.com%2Flive-cricket-...,4.58514,"103.48.46.23, 23.63.110.60, 23.57.76.153",1,178,B681N654k146,1.000,16.0,"333,493,333,494",NaN,205295-1,1,103.48.46.23,144.0,0.0,4.0,NaN,8.0,NaN,AdServe,103.48.46.23,144,144,348011.0,0.0,NaN,1804.0,348027.0,132590.0,129300.0,199522.0,196047.0,196460.0,202038.0,264494,129639.0,NaN,NaN,NaN,NaN,NaN

In [23]:
click_log_nunique = click_log.agg(['nunique']).transpose().reset_index()
click_log_nunique.columns = ['column', 'unique_value_count']

In [26]:
click_log.shape

(244864, 55)

In [24]:
display(click_log_nunique)

                       column  unique_value_count
0                  Unnamed: 0                   1
1                      imprId              230166
2                  clmbUserId              218003
3                  adSltDimId                1874
4                        auds               66148
5                     allAuds              169453
6                      itemid                1938
7                        algo                  13
8                 advClientId                 179
9                 pubClientId                 153
10                 itmClmbLId                 849
11                    tmpltId                 606
12                     refUrl               33246
13                   clickBid                2048
14         clickXForwardedFor              218243
15                   position               18115
16                       paid                   1
17                     siteId                 406
18             callIdentifier              206322
19                       crtd                   1
20                adslotRatio                 713
21                pricingType                 475
22               usrClusterId                3655
23             siteClusterIds                1444
24                   ctxCatId                 923
25                 uuidSource               69329
26                    clickIp               79517
27                 clickGeoId                  16
28                        esi                   7
29  adBlockerDetectionValueId                2577
30                   bundleId                3786
31  impressionServedTimeStamp               18829
32                     appver               28931
33                      topic               39949
34                         ip              132417
35                   geoDimId                 167
36               countryDimId                 340
37                geoGrpDimId                 575
38                  cityDimId                 307
39               cityGrpDimId                 527
40                 stateDimId                 671
41              stateGrpDimId                 762
42                   ispDimId                1365
43                    osDimId                 223
44                 osVerDimId                 437
45               devTypeDimId                 302
46                vendorDimId                 674
47                 modelDimId                3763
48              connTypeDimId                3101
49               browserDimId                 391
50               refClusterId                5525
51                      fraud                2379
52                        cpa                 714
53                 imprUserId                1588
54                     optout                 543

In [31]:
click_log_drop_cols = click_log_nunique.loc[(click_log_nunique.unique_value_count == 1) | 
                                            (click_log_nunique.unique_value_count == click_log.shape[0]),
                                           'column'].values.tolist()

click_log = click_log.drop(columns=click_log_drop_cols, errors='ignore')

In [25]:
click_log_missing = missing_value_stats(click_log)

display(click_log_missing)

                       column  missing_values  missing_percentage
0                        auds           63035               25.74
1                     allAuds           13335                5.45
2                     tmpltId           22299                9.11
3                      refUrl           46450               18.97
4                    clickBid          103006               42.07
5          clickXForwardedFor           22299                9.11
6              callIdentifier            1140                0.47
7                 adslotRatio           29667               12.12
8                 pricingType           22299                9.11
9                usrClusterId           84280               34.42
10             siteClusterIds           56720               23.16
11                   ctxCatId           18407                7.52
12                 uuidSource            8112                3.31
13                    clickIp           22299                9.11
14                 clickGeoId           22299                9.11
15                        esi           81514               33.29
16  adBlockerDetectionValueId          108712               44.40
17                   bundleId          143999               58.81
18  impressionServedTimeStamp           88104               35.98
19                     appver          117879               48.14
20                geoGrpDimId           11380                4.65
21                  cityDimId            6089                2.49
22               cityGrpDimId           34603               14.13
23                 stateDimId            2749                1.12
24              stateGrpDimId            9945                4.06
25                   ispDimId             132                0.05
26                    osDimId             221                0.09
27                 osVerDimId             245                0.10
28               devTypeDimId           15356                6.27
29                vendorDimId            5880                2.40
30                 modelDimId           22615                9.24
31              connTypeDimId           60499               24.71
32               browserDimId           80265               32.78
33               refClusterId          188613               77.03
34                      fraud          224177               91.55
35                        cpa          191388               78.16
36                 imprUserId          193857               79.17
37                     optout          224546               91.70

In [32]:
click_log['fraud'].unique()

array([nan, True, 'TRUE', ..., 333727.0, 333489.0, 333506.0], dtype=object)

In [21]:
os.makedirs('data/cleaned', exist_ok=True)

df_train.to_csv('data/cleaned/train.csv', index=False)